### ISSUE TITLE
Missing import for run_align_emergent_data.py

### ISSUE THREAD

**Issue by isabelleaugenstein** [willferreira/mscproject#1]
Update README: explain what package needs to be installed to run run_align_emergent_data.py

$ python run_align_emergent_data.py 
Traceback (most recent call last):
  File "run_align_emergent_data.py", line 8, in <module>
    from aligner import align
ImportError: No module named aligner

**Comment by willferreira** [comment]
I think that code refers to an alignment algorithm that was deprecated in favour of the Hungarian alignment algorithm. Therefore I would ignore the failure of that script.
