### ISSUE TITLE
Run on another dataset

### ISSUE THREAD

**Issue by JoaoLages** [willferreira/mscproject#2]
How can I run the code on another dataset?
Furthermore, I've followed the instructions but I got really confused at the end. I dont know how to analyze the output folder.

**Comment by andreasvlachos** [comment]
You will probably need to write some extra code probably to run this on a different dataset. The run_train_test.py shows how you could do it assuming you write the code to load the data. As for how to analyze the output folder, could you be more specific?

**Comment by JoaoLages** [comment]
Thanks for the reply! I will try to change run_train_test.py then.
By analyzing the output folder I meant that I don't know what the xml and txt files represent.

**Comment by willferreira** [comment]
Sorry my reply was incomplete! That code was written specifically for that data so I'm not sure it can be used for other data. I will take a look at the code and try to recall what the output folder is meant to contain. What is your interest in the code?

Will

Sent from my HTC

----- Reply message -----

**Comment by andreasvlachos** [comment]
Assuming that you are interested in the fake news challenge, you might want to look at the baseline code released there too.

**Comment by willferreira** [comment]
I agree with Andreas. The fakenewschallenge baseline is preferable as your first port of call as you will likely get it to run more easily.

Will

Sent from my HTC

----- Reply message -----

**Comment by JoaoLages** [comment]
Ok, I will have a look at the baseline code of FNC.
Thank you!
