### ISSUE TITLE
Question about SVO

### ISSUE THREAD

**Issue by shsh88** [willferreira/mscproject#6]
Hi,
I have some questions that I could not find answers to in your code and in the paper related and it would be very helpful if you could answer them please...

What did you do in case there is no svo triple in the title:
example:
title:
" Banksy 'Arrested & Real Identity Revealed' Is The Same Hoax From Last Year "
will give the following dependency:

root(ROOT-0, Arrested-3)
nsubj(Arrested-3, Banksy-1)
punct(Arrested-3, `-2)
cc(Arrested-3, &-4)
compound(Revealed-7, Real-5)
compound(Revealed-7, Identity-6)
nsubj(Hoax-12, Revealed-7)
case(Revealed-7, '-8)
cop(Hoax-12, Is-9)
det(Hoax-12, The-10)
amod(Hoax-12, Same-11)
conj:&(Arrested-3, Hoax-12)
case(Year-15, From-13)
amod(Year-15, Last-14)
nmod:from(Hoax-12, Year-15)

So there is no 'dobj' here...

And what did you do in case there are more than on svo triple in the text ? It is mentioned that a triple is taken for each the claim and the title, but how did you would determine which triple.. 

Thanks in advance,
Kind regards,

**Comment by andreasvlachos** [comment]
Greetings,

Will's MSc thesis has some more details than the paper. If you send me an email, I will send it to you. In short if no SVO triple is found nothing happens. If there are multiple ones, the counts of the features extracted for each are simply added.

Best,
Andreas
